#!/bin/bash
function start {
	mkdir -p ./tmp
	mkdir -p ./tmp/pids
	
	echo "Starting the worker processes..."
	PIDFILE=./tmp/pids/migrations0.pid BACKGROUND=yes QUEUE=migrations bundle exec rake resque:work
	
	PIDFILE=./tmp/pids/migrations1.pid BACKGROUND=yes QUEUE=migrations bundle exec rake resque:work
	
	PIDFILE=./tmp/pids/migrations2.pid BACKGROUND=yes QUEUE=migrations bundle exec rake resque:work
	echo "Done"
}

function stop {
	echo "Stopping the rescue processes..."

	if [ -f ./tmp/pids/migrations0.pid ]; then
		kill -9 `cat ./tmp/pids/migrations0.pid`
		rm ./tmp/pids/migrations0.pid
	fi
	
	if [ -f ./tmp/pids/migrations1.pid ]; then
		kill -9 `cat ./tmp/pids/migrations1.pid`
		rm ./tmp/pids/migrations1.pid
	fi
	
	if [ -f ./tmp/pids/migrations2.pid ]; then
		kill -9 `cat ./tmp/pids/migrations2.pid`
		rm ./tmp/pids/migrations2.pid
	fi

	echo "Done"
}

if [ $1 == 'start' ]; then
	start
fi

if [ $1 == 'stop' ]; then
	stop
fi

if [ $1 == 'restart' ]; then
	stop
	start
fi