#!/bin/bash
function start {
	mkdir -p ./tmp
	mkdir -p ./tmp/pids
	
	echo "Starting the worker processes..."
	RACK_ENV=$ENVIRONMENT PIDFILE=./tmp/pids/migrations0.pid QUEUE=migrations bundle exec rake resque:work > worker1.log &
	
	RACK_ENV=$ENVIRONMENT PIDFILE=./tmp/pids/migrations1.pid QUEUE=migrations bundle exec rake resque:work > worker2.log & 
	
	RACK_ENV=$ENVIRONMENT PIDFILE=./tmp/pids/migrations2.pid QUEUE=migrations bundle exec rake resque:work > worker3.log &
	echo "Done"
}

function stop {
	echo "Stopping the rescue processes..."

	if [ -f ./tmp/pids/migrations0.pid ]; then
		kill -9 `cat ./tmp/pids/migrations0.pid`
		rm ./tmp/pids/migrations0.pid
	fi
	
	if [ -f ./tmp/pids/migrations1.pid ]; then
		kill -9 `cat ./tmp/pids/migrations1.pid`
		rm ./tmp/pids/migrations1.pid
	fi
	
	if [ -f ./tmp/pids/migrations2.pid ]; then
		kill -9 `cat ./tmp/pids/migrations2.pid`
		rm ./tmp/pids/migrations2.pid
	fi

	echo "Done"
}

if [ $1 == 'start' ]; then
	ENVIRONMENT="local"
	if [ -n "$2" ]; then
		ENVIRONMENT=$2
	fi
		
	start
fi

if [ $1 == 'stop' ]; then
	ENVIRONMENT="local"
	if [ -n "$2" ]; then
		ENVIRONMENT=$2
	fi
	
	stop
fi

if [ $1 == 'restart' ]; then
	ENVIRONMENT="local"
	if [ -n "$2" ]; then
		ENVIRONMENT=$2
	fi
	
	stop
	start
fi